export const SAVE_ERRORS = 'SAVE_ERRORS';
export const SAVE_CREATE_POST = 'SAVE_CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';
export const SAVE_POSTS = 'SAVE_POSTS';
export const SAVE_SELECTED_POST = 'SAVE_SELECTED_POST';